name: Deploy TeamManagement App to Ubutnu server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish Blazor app
      run: dotnet publish -c Release -o publish

    - name: Copy files to Hetzner server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HETZNER_HOST }}
        username: ${{ secrets.HETZNER_USER }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        source: publish/
        target: /var/www/teammanagement/

    - name: Restart and set env vars
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HETZNER_HOST }}
        username: ${{ secrets.HETZNER_USER }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        script: |
          export ConnectionStrings__DefaultConnection='${{ secrets.SQL_CONNECTION_STRING }}'
          sudo systemctl restart myapp

