name: Deploy TeamManagement App to Ubuntu server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish Blazor app
      run: dotnet publish -c Release -o publish

    - name: Copy files to Hetzner server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HETZNER_HOST }}
        username: ${{ secrets.HETZNER_USER }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        source: publish/
        target: /var/www/teammanagement/

    - name: Inject connection string and restart service
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HETZNER_HOST }}
        username: ${{ secrets.HETZNER_USER }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        script: |
          sudo sed -i '/^Environment=ConnectionStrings__/d' /etc/systemd/system/teamManagement.service
          echo "Environment=ConnectionStrings__DefaultConnection=${{ secrets.SQL_CONNECTION_STRING }}" | sudo tee -a /etc/systemd/system/teamManagement.service
          sudo systemctl daemon-reexec
          sudo systemctl daemon-reload
          sudo systemctl restart teamManagement

    - name: Verify deployment via health check
      run: |
        echo "Waiting 10 seconds for app to become available..."
        sleep 10
        echo "Pinging https://app.su-leisach.com ..."
        curl -f --retry 5 --retry-delay 5 https://app.su-leisach.com
